### ISSUE TITLE
An error raised during loading NYUD pretrained model

### ISSUE THREAD

**Issue by Li-yachuan** [MengyangPu/EDTER#41]
Thanks for your amazing work at first. But I meet an error when test the NYUD pretrained model. I hope I could get your help.
I have tested the BSDS pretrained model successfully. But when test NYUD pretrained model you provide, an error raises.
I am not proficient in mmseg, so I cannot solve it independently. I am looking forward to your reply. Thank you very much
![image](https://user-images.githubusercontent.com/44263056/199444005-465ff3ba-012b-4ccc-917f-0d6da3a1e657.png)

**Comment by chengyiyi1** [comment]
Bro, have you solved this problem? This problem occurred when I used the BSDS pre-training model. I am looking forward to your reply. Thank you very much！

**Comment by Yachuan-Li** [comment]
We can use bilinear to make the smaller one of all the matrices whose size is not the same as the larger one.


---Original--
From: ***@***.***&gt;
Date: Thu, Dec 29, 2022 10:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrainedmodel (Issue #41)




 
Bro, have you solved this problem? This problem occurred when I used the BSDS pre-training model. I am looking forward to your reply. Thank you very much！

**Comment by chengyiyi1** [comment]
Thank you very much for your reply! Can you be more specific? Due to limited knowledge, I am not able to understand, and look forward to your reply!



程伊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MengyangPu/EDTER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月29日(星期四) 中午11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrained model (Issue #41)





 We can use bilinear to make the smaller one of all the matrices whose size is not the same as the larger one. 
 
 
 ---Original-- 
 From: ***@***.***&amp;gt; 
 Date: Thu, Dec 29, 2022 10:16 AM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrainedmodel (Issue #41) 
 
 
 
 
   
 Bro, have you solved this problem? This problem occurred when I used the BSDS pre-training model. I am looking forward to your reply. Thank you very much！

**Comment by Yachuan-Li** [comment]
mmseg/models/segmentors/encoder_decoder.py
388行左右
preds=img.new_zeros((batch_size,64,h_img,w_img))
适用于nyud


preds=img.new_zeros((batch_size,128,h_img,w_img))

适用于bsds



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 29, 2022 13:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrained model (Issue #41)




 Thank you very much for your reply! Can you be more specific? Due to limited knowledge, I am not able to understand, and look forward to your reply! 
 
 
 
 程伊 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "MengyangPu/EDTER"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年12月29日(星期四) 中午11:48 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrained model (Issue #41) 
 
 
 
 
 
  We can use bilinear to make the smaller one of all the matrices whose size is not the same as the larger one.  
   
   
  ---Original--  
  From: ***@***.***&amp;amp;gt;  
  Date: Thu, Dec 29, 2022 10:16 AM  
  To: ***@***.***&amp;amp;gt;;  
  Cc: ***@***.******@***.***&amp;amp;gt;;  
  Subject: Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrainedmodel (Issue #41)  
   
   
   
   
     
  Bro, have you solved this problem? This problem occurred when I used the BSDS pre-training model. I am looking forward to your reply. Thank you very much！

**Comment by chengyiyi1** [comment]
谢谢您的回复！！
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 我再尝试一下！



程伊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MengyangPu/EDTER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月29日(星期四) 晚上10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrained model (Issue #41)





 mmseg/models/segmentors/encoder_decoder.py 
 388行左右 
 preds=img.new_zeros((batch_size,64,h_img,w_img)) 
 适用于nyud 
 
 
 preds=img.new_zeros((batch_size,128,h_img,w_img)) 
 
 适用于bsds 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Thu, Dec 29, 2022 13:24 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrained model (Issue #41) 
 
 
 
 
  Thank you very much for your reply! Can you be more specific? Due to limited knowledge, I am not able to understand, and look forward to your reply!  
   
   
   
  程伊  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "MengyangPu/EDTER"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年12月29日(星期四) 中午11:48  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrained model (Issue #41)  
   
   
   
   
   
   We can use bilinear to make the smaller one of all the matrices whose size is not the same as the larger one.   
     
     
   ---Original--   
   From: ***@***.***&amp;amp;amp;gt;   
   Date: Thu, Dec 29, 2022 10:16 AM   
   To: ***@***.***&amp;amp;amp;gt;;   
   Cc: ***@***.******@***.***&amp;amp;amp;gt;;   
   Subject: Re: [MengyangPu/EDTER] An error raised during loading NYUD pretrainedmodel (Issue #41)   
     
     
     
     
       
   Bro, have you solved this problem? This problem occurred when I used the BSDS pre-training model. I am looking forward to your reply. Thank you very much！
